# Generated by Django 3.1.2 on 2020-11-17 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('movie', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date(2020, 11, 16))),
            ],
        ),
    ]
